baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Bojanorama"

[params]
description = "Ramblings on social science, social networks, statistics, game theory and alike"
